# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: gateway 
#   namespace: default 
# spec:
#   rules:
#     - host: gateway.ctnrs.com 
#       http:
#         paths:
#         - path: /
#           backend:
#             serviceName: gateway
#             servicePort: 9999
# ---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
spec:
  ports:
  - port: 9091
    name: gateway
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: gateway
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: gateway
        image: 192.168.134.104/commodity/gateway:v1.0
        imagePullPolicy: Always
        ports:
          - protocol: TCP
            containerPort: 9092
        env:
          - name: ETCD_DIAL_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: commodity-configmap
                key: etcddialtimeout
          - name: ETCD_END_POINT
            valueFrom:
              configMapKeyRef:
                name: commodity-configmap
                key: etcdendpoint
          - name: CONFIG_KEY
            valueFrom:
              configMapKeyRef:
                name: commodity-configmap
                key: configkey
        resources:
          requests:
            cpu: 2
            memory: 256Mi
          limits:
            cpu: 4
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 10
