apiVersion: apps/v1
kind: Deployment 
metadata:
  name: item
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item
  template:
    metadata:
      labels:
        app: item
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: item
        image: 192.168.134.104/commodity/item:v1.0
        imagePullPolicy: Always
        env:
          - name: ETCD_DIAL_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: commodity-configmap
                key: etcddialtimeout
          - name: ETCD_END_POINT
            valueFrom:
              configMapKeyRef:
                name: commodity-configmap
                key: etcdendpoint
          - name: CONFIG_KEY
            valueFrom:
              configMapKeyRef:
                name: commodity-configmap
                key: configkey
        resources:
          requests:
            cpu: 2
            memory: 256Mi
          limits:
            cpu: 4
            memory: 256Mi
        readinessProbe:
          exec:
            command:
            - /bin/sh 
            - -c
            - ps -ef | grep item | grep -v grep 
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh 
            - -c
            - ps -ef | grep item | grep -v grep 
          initialDelaySeconds: 5
          periodSeconds: 10
